apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413556168018:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MS86ZRRXACG5
      username: system:node:{{EC2PrivateDNSName}}
      -system:masters
      rolearn: arn:aws:iam::413556168018:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-21T19:03:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "136162"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e90fbca1-83dd-4aba-a053-95fbe8c3cd0d
